exclude = [
    "CodeSnippets",
    "CodeGenerationOutputs",
    "docs",
    "Documentation",
    "CodeGenerationLogs",
    "PatternRecommender/Output",
    "PatternRecommender/Input",
    "PatternRecogniser/Input"
]