"""
================================================================================
AI-GENERATED CODE DISCLAIMER
================================================================================
This file was fully generated by AI using Claude Sonnet 4.6 on 10/04/2026.

Purpose: Analyse generated F1 result and summarise them into a single file
================================================================================
"""

import glob
import re
from pathlib import Path

INPUT_PATTERN = "f1_*.txt"
OUTPUT_FILE   = "combined_results.txt"

def parse_f1_file(path):
    model_name = re.sub(r"^f1_", "", Path(path).stem).capitalize()
    patterns = {}
    total_correct = total_samples = 0

    with open(path) as f:
        for line in f:
            m = re.match(
                r"(\w+)\s+(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)",
                line.strip()
            )
            if m:
                name, tp, fp, fn, prec, rec, f1 = m.groups()
                if name.upper() == "AVG":
                    continue
                patterns[name] = {
                    "tp": int(tp), "fp": int(fp), "fn": int(fn),
                    "precision": float(prec), "recall": float(rec), "f1": float(f1)
                }

            acc = re.search(r"(\d+)/(\d+)\s*=\s*[\d.]+", line)
            if acc:
                total_correct = int(acc.group(1))
                total_samples = int(acc.group(2))

    macro_f1 = sum(v["f1"] for v in patterns.values()) / len(patterns)
    accuracy  = total_correct / total_samples if total_samples else 0

    return model_name, patterns, macro_f1, accuracy, total_correct, total_samples


def compute_combined(all_models):
    combined = {}
    for _name, patterns, *_ in all_models:
        for pat, stats in patterns.items():
            if pat not in combined:
                combined[pat] = {"tp": 0, "fp": 0, "fn": 0}
            combined[pat]["tp"] += stats["tp"]
            combined[pat]["fp"] += stats["fp"]
            combined[pat]["fn"] += stats["fn"]

    for pat, s in combined.items():
        tp, fp, fn = s["tp"], s["fp"], s["fn"]
        s["precision"] = tp / (tp + fp) if (tp + fp) else 0
        s["recall"]    = tp / (tp + fn) if (tp + fn) else 0
        p, r = s["precision"], s["recall"]
        s["f1"]        = 2 * p * r / (p + r) if (p + r) else 0

    return combined


def best_models(pattern, all_models):
    scores = {name: pats[pattern]["f1"] for name, pats, *_ in all_models if pattern in pats}
    top = max(scores.values())
    winners = [n for n, v in scores.items() if v == top]
    return "All equal" if len(winners) == len(all_models) else "/".join(winners)


def write_output(all_models, combined, output_path):
    pattern_order = list(next(pats for _, pats, *_ in all_models))
    model_names   = [name for name, *_ in all_models]

    lines = []
    sep = "=" * 60

    lines += [
        sep,
        "  COMBINED F1 RESULTS - DESIGN PATTERN DETECTION BENCHMARK",
        sep,
        "",
    ]

    # --- Overall accuracy ---
    lines += [
        "OVERALL ACCURACY",
        "-" * 17,
        f"{'Rank':<6}{'Model':<10}{'Accuracy':<16}{'F1 (Macro)':<13}{'Correct / Total'}",
    ]
    sorted_models = sorted(all_models, key=lambda x: x[2], reverse=True)
    for rank, (name, _pats, macro_f1, acc, correct, total) in enumerate(sorted_models, 1):
        lines.append(
            f"  {rank}   {name:<10}{acc:<16.3f}{macro_f1:<13.3f}{correct} / {total}"
        )
    lines.append("")

    # --- Per-pattern F1 ---
    lines += [
        "",
        "PER-PATTERN F1 SCORES",
        "-" * 22,
        f"{'Pattern':<14}" + "".join(f"{n:>8}" for n in model_names) + f"{'Best':>14}",
        "-" * 60,
    ]
    macro_per_model = {name: [] for name, *_ in all_models}
    for pat in pattern_order:
        scores = [pats[pat]["f1"] for _, pats, *_ in all_models]
        for (name, pats, *_), s in zip(all_models, scores):
            macro_per_model[name].append(s)
        best = best_models(pat, all_models)
        row = f"{pat:<14}" + "".join(f"{s:>8.3f}" for s in scores) + f"    {best}"
        lines.append(row)
    lines.append("-" * 60)
    avgs = [sum(macro_per_model[n]) / len(macro_per_model[n]) for n in model_names]
    lines.append(f"{'Macro Avg':<14}" + "".join(f"{a:>8.3f}" for a in avgs))
    lines.append("")

    # --- Combined F1 ---
    lines += [
        "",
        "COMBINED F1 (ALL MODELS)",
        "-" * 26,
        f"{'Pattern':<18}{'TP':>6}{'FP':>6}{'FN':>6}  {'Precision':>9}  {'Recall':>8}  {'F1':>8}",
        "-" * 65,
    ]
    total_tp = total_fp = total_fn = 0
    prec_sum = rec_sum = f1_sum = 0
    for pat in pattern_order:
        s = combined[pat]
        lines.append(
            f"{pat:<18}{s['tp']:>6}{s['fp']:>6}{s['fn']:>6}"
            f"  {s['precision']:>9.3f}  {s['recall']:>8.3f}  {s['f1']:>8.3f}"
        )
        total_tp += s["tp"]; total_fp += s["fp"]; total_fn += s["fn"]
        prec_sum += s["precision"]; rec_sum += s["recall"]; f1_sum += s["f1"]

    n = len(pattern_order)
    lines += [
        "-" * 65,
        f"{'MACRO AVG':<30}  {prec_sum/n:>9.3f}  {rec_sum/n:>8.3f}  {f1_sum/n:>8.3f}",
        "",
        f"Overall Accuracy: {total_tp}/{total_tp + total_fn} = {total_tp / (total_tp + total_fn):.3f}",
        sep,
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written to {output_path}")


def main():
    files = sorted(glob.glob(INPUT_PATTERN))
    if not files:
        raise FileNotFoundError(f"No files matching '{INPUT_PATTERN}' found.")

    print(f"Found {len(files)} input file(s): {', '.join(files)}")
    all_models = [parse_f1_file(p) for p in files]
    combined   = compute_combined(all_models)
    write_output(all_models, combined, OUTPUT_FILE)


if __name__ == "__main__":
    main()