"""
================================================================================
AI-GENERATED CODE DISCLAIMER
================================================================================
This file was fully generated by AI using Claude Sonnet 4.6 on 25/02/2026.

Purpose: Analyse pattern recognition performance by calculating precision, recall, and F1 scores

The script reads an Excel file with columns "Snippet_name" and "Identified pattern". 
It extracts the expected pattern from the filename, compares it to the identified pattern, 
and computes true positives, false positives, and false negatives for each pattern. 

Finally, it calculates and prints precision, recall, F1 score for each pattern, as well as macro averages and overall accuracy.
================================================================================
"""


import pandas as pd
from collections import defaultdict

def extract_expected_pattern(snippet_name):
    """Extract pattern from filename e.g. Adapter_0_E_GROK4F.py -> Adapter"""
    return snippet_name.split("_")[0]

def calculate_metrics(filepath):
    df = pd.read_excel(filepath)

    # Validate columns
    required = ["Snippet_name", "Identified pattern"]
    for col in required:
        if col not in df.columns:
            raise ValueError(f"Missing column: '{col}'")

    TP = defaultdict(int)
    FN = defaultdict(int)
    FP = defaultdict(int)

    for _, row in df.iterrows():
        expected   = extract_expected_pattern(str(row["Snippet_name"]))
        identified = str(row["Identified pattern"]).strip()

        if expected == identified:
            TP[expected] += 1
        else:
            FN[expected]    += 1  # true pattern was missed
            FP[identified]  += 1  # wrong pattern was falsely claimed

    # Per-pattern metrics
    all_patterns = set(list(TP.keys()) + list(FN.keys()) + list(FP.keys()))

    print(f"\n{'Pattern':<15} {'TP':>5} {'FP':>5} {'FN':>5} {'Precision':>10} {'Recall':>10} {'F1':>10}")
    print("-" * 65)

    macro_precision, macro_recall, macro_f1 = [], [], []

    for pattern in sorted(all_patterns):
        tp = TP[pattern]
        fp = FP[pattern]
        fn = FN[pattern]

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1        = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

        macro_precision.append(precision)
        macro_recall.append(recall)
        macro_f1.append(f1)

        print(f"{pattern:<15} {tp:>5} {fp:>5} {fn:>5} {precision:>10.3f} {recall:>10.3f} {f1:>10.3f}")

    # Macro averages
    print("-" * 65)
    print(f"{'MACRO AVG':<15} {'':>5} {'':>5} {'':>5} "
          f"{sum(macro_precision)/len(macro_precision):>10.3f} "
          f"{sum(macro_recall)/len(macro_recall):>10.3f} "
          f"{sum(macro_f1)/len(macro_f1):>10.3f}")

    # Overall accuracy
    total_tp = sum(TP.values())
    total    = total_tp + sum(FN.values())
    print(f"\nOverall Accuracy: {total_tp}/{total} = {total_tp/total:.3f}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python f1_score.py <path_to_xlsx>")
        sys.exit(1)

    calculate_metrics(sys.argv[1])