"""
Analysis Generator
Reads Excel reports generated by report_generator.py 
and produces comprehensive statistical analysis in JSON format
"""
import os
import json
from typing import List, Dict, Any, Callable
from datetime import datetime
import pandas as pd
from pathlib import Path
from catalogue import DESIGN_PATTERNS


class AnalysisGenerator:
    """ Generate analysis from Excel reports """
    
    def __init__(self, reports_dir: str = "./Reports", output_dir: str = "./Analysis"):
        """ Initialise the AnalysisGenerator """
        self.reports_dir = reports_dir
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Store calculation methods
        self.calculation_methods: List[Callable] = [
            self._calculate_total_analysis_time,
            self._calculate_average_analysis_time,
            self._calculate_success_rate_per_pattern
        ]
    
    def get_excel_reports(self) -> List[Path]:
        """ Get all Excel report files from the reports directory """
        if not os.path.exists(self.reports_dir):
            raise FileNotFoundError(f"Reports directory not found: {self.reports_dir}")
        
        excel_files = list(Path(self.reports_dir).glob("report_*.xlsx"))
        
        if not excel_files:
            raise FileNotFoundError(f"No Excel reports found in {self.reports_dir}")
        
        return excel_files
    
    def load_single_excel_report(self, file_path: Path) -> pd.DataFrame:
        """ Load a single Excel report """
        try:
            df = pd.read_excel(file_path)
            print(f"Loaded: {file_path.name} ({len(df)} records)")
            return df
        except Exception as e:
            raise Exception(f"Error loading {file_path.name}: {e}")
    
    def extract_llm_name_from_filename(self, file_path: Path) -> str:
        """ Extract LLM name from filename """
        # Get filename without extension
        filename = file_path.stem  # Get filename without extension
        llm_name = filename.replace('report_', '')
        return llm_name
    


    ############################ CALCULATIONS ############################
    def _calculate_total_analysis_time(self, df: pd.DataFrame) -> Dict[str, Any]:
        """Calculate total analysis time across all records"""
        total_time = df['Analysis_time'].sum()
        return {
            "total_analysis_time_seconds": round(float(total_time), 2),
            "total_analysis_time_minutes": round(float(total_time / 60), 2),
            "total_analysis_time_hours": round(float(total_time / 3600), 2)
        }
    
    def _calculate_average_analysis_time(self, df: pd.DataFrame) -> Dict[str, Any]:
        """Calculate average analysis time statistics."""
        return {
            "average_analysis_time_seconds": round(df['Analysis_time'].mean(), 2),
            "min_analysis_time_seconds": round(df['Analysis_time'].min(), 2),
            "max_analysis_time_seconds": round(df['Analysis_time'].max(), 2)
        }
 
    def _calculate_success_rate_per_pattern(self, df: pd.DataFrame) -> Dict[str, Any]:
        """Calculate success rates for each design pattern."""
        success_rates = {}
        
        for pattern in DESIGN_PATTERNS:
            pattern_df = df[df['Identified pattern'] == pattern]
            
            if len(pattern_df) > 0:
                success_rates[pattern] = {
                    "success_rate": round(pattern_df['Success'].mean(), 2),
                    "total_count": int(len(pattern_df)),
                    "success_count": int(pattern_df['Success'].sum()),
                    "failure_count": int((~pattern_df['Success']).sum())
                }
        
        return {"success_rate_per_pattern": success_rates}
    
    
    
    def generate_analysis_for_llm(self, df: pd.DataFrame, llm_name: str) -> Dict[str, Any]:
        """
        Execute all calculation methods for a single LLM's data
        """
        # Initialise results dictionary
        analysis_results = {
            "metadata": {
                "llm_name": llm_name,
                "generation_timestamp": datetime.now().isoformat(),
                "reports_directory": self.reports_dir,
                "total_records_analysed": int(len(df))
            }
        }
        
        # Execute all calculation methods
        for calc_method in self.calculation_methods:
            try:
                result = calc_method(df)
                analysis_results.update(result)
                print(f"[SUCCESS] Completed: {calc_method.__name__}")
            except Exception as e:
                print(f"[FAILED] Error in {calc_method.__name__}: {e}")
                analysis_results[calc_method.__name__] = {"error": str(e)}
        
        return analysis_results
    
    def save_analysis_to_json(self, analysis_data: Dict[str, Any], llm_name: str) -> str:
        """ Save analysis results to JSON """
        filename = f"analysis_{llm_name}.json"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(analysis_data, f, indent=2, ensure_ascii=False)
        
        print(f"  [SUCCESS] Analysis saved to: {filepath}\n")
        return filepath
    
    def run(self) -> List[str]:
        """ process each LLM report separately """
        print("="*60)
        print("Starting Analysis Generation")
        print("="*60)
        
        # Get all Excel reportS
        excel_files = self.get_excel_reports()
        output_files = []
        
        # Process each report
        for file_path in excel_files:
            print(f"\nProcessing: {file_path.name}")
            print("-"*60)
            
            try:
                # Extract LLM name
                llm_name = self.extract_llm_name_from_filename(file_path)
                
                # Load report
                df = self.load_single_excel_report(file_path)
                
                # Generate analysis
                analysis_results = self.generate_analysis_for_llm(df, llm_name)
                
                # Save to JSON
                output_path = self.save_analysis_to_json(analysis_results, llm_name)
                output_files.append(output_path)
                
            except Exception as e:
                print(f"[ERROR] Failed to process {file_path.name}: {e}\n")
        
        print("="*60)
        print("Analysis Generation Complete")
        print(f"Processed {len(output_files)} LLM reports")
        print("="*60)
        
        return output_files


def main():
    """Example usage of AnalysisGenerator."""
    # Initialise the generator
    generator = AnalysisGenerator(
        reports_dir="./Reports",
        output_dir="./Analysis"
    )
    
    # Run the complete analysis
    try:
        output_files = generator.run()
        print(f"\n[Success] Generated {len(output_files)} analysis reports:")
        for file in output_files:
            print(f"- {Path(file).stem}")
    except Exception as e:
        print(f"\nError: {e}")


if __name__ == "__main__":
    main()