from enum import Enum
import os
from typing import Final

# Workflow type
class WorkflowType(str, Enum):
    SINGLE_PROMPT = "single_prompt"
    MULTI_LAYERED = "multi_layered"

# Availabvle patterns
# Using Tuple for immutability (as it's final)
DESIGN_PATTERNS: Final[tuple[str, ...]] = (
    "Singleton", "Factory", "Builder", "Prototype",
    "Adapter", "Decorator", "Facade", "Proxy",
    "Observer", "Strategy", "Command", "Iterator", "State"
)

# Available difficulty levels
DIFFICULTY_LEVELS: Final[tuple[str, ...]] = ("E", "M", "H")

# LLM providers
LLM_PROVIDERS: Final[tuple[str, ...]] = (
    "ollama",
    "openai",
    "claude",

    "kimi",
    "grok",
    "grok4fast",
    "qwen",
)

# PREFIX - PROVIDER
LLM_SHORT_MAP: Final[dict[str, str]] = {
    "L": "ollama",
    "O": "openai",
    "C": "claude",

    "Kimi2": "kimi",
    "GROK": "grok",
    "GROK4F": "grok4fast",
    "Q3C": "qwen",
}


############### UTILS ###############

def get_llm_prefix(name:str) -> str:
    for prefix, provider in LLM_SHORT_MAP.items():
        if provider == name:
            return prefix
    
    return None

def is_file_generated_by_llm(filename: str, llm_name: str) -> bool:

    """Check if the given file was generated by the specified LLM provider."""
    # get prefix from given llm name
    expected_prefix = get_llm_prefix(llm_name)
    if expected_prefix is None:
        return False
    
    # Extract just the filename
    filename = os.path.basename(filename)
    
    # Abort is file is not a python script
    if not filename.endswith(".py"):
        return False
    
    # Split formatted filename structure
    parts = filename[:-3].split("_")
    if len(parts) < 4:
        return False
    
    # Get file llm_prefix and compare
    file_prefix = parts[-1]
    return file_prefix == expected_prefix


def parse_filename(filename: str) -> dict[str, str]:
    """Parse filename {design_pattern}_{id}_{difficulty}_{llm}.py"""
    
    if not filename.endswith(".py"):
        raise ValueError(f"Filename must end with '.py' {filename}")
    
    parts = filename[:-3].split('_') # remove .py and split
    if len(parts) != 4:
        raise ValueError("Filename must follow the pattern {design_pattern}_{id}_{difficulty}_{llm}.py")
    
    pattern, id, difficulty, llm = parts

    # Validate parts
    if not pattern:
        raise ValueError(f'Design pattern cannot be empty: {filename}')
    if not id.isdigit():
        raise ValueError(f'ID must be numeric: {filename}')
    if difficulty not in DIFFICULTY_LEVELS:
        raise ValueError(f'Difficulty must be one of: {",".join(DIFFICULTY_LEVELS)}')
    if not llm:
        raise ValueError(f'LLM prefix cannot be empty: {filename}')
    
    return {
        'pattern': pattern,
        'id': id,
        'difficulty': difficulty,
        'llm': llm
    }

