"""
================================================================================
AI-GENERATED CODE DISCLAIMER
================================================================================
This file was fully generated by AI using Claude Sonnet 4.5 on 01/10/2025.

Purpose: Visual representation of design pattern recognition analysis data
         collected from various LLM models.

The script automatically processes analysis JSON files and generates
comprehensive visualisation charts for performance comparison.
================================================================================
"""

import matplotlib.pyplot as plt
import numpy as np
import json
from pathlib import Path

def load_analysis_files(analysis_dir):
    """Load all analysis JSON files from the specified directory."""
    analysis_path = Path(analysis_dir)
    json_files = list(analysis_path.glob("analysis_*.json"))
    
    if not json_files:
        print(f"No analysis files found in {analysis_dir}")
        return []
    
    data_list = []
    for json_file in json_files:
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
                data['_filename'] = json_file.name
                data_list.append(data)
            print(f"✓ Loaded: {json_file.name}")
        except Exception as e:
            print(f"✗ Error loading {json_file.name}: {e}")
    
    return data_list

def create_visualisation(data, output_path):
    """Create visualisation for a single analysis dataset."""
    llm_name = data["metadata"]["llm_name"]
    
    # Extract pattern data
    patterns = list(data["success_rate_per_pattern"].keys())
    success_rates = [data["success_rate_per_pattern"][p]["success_rate"] for p in patterns]
    total_counts = [data["success_rate_per_pattern"][p]["total_count"] for p in patterns]
    failure_counts = [data["success_rate_per_pattern"][p]["failure_count"] for p in patterns]
    success_counts = [data["success_rate_per_pattern"][p]["success_count"] for p in patterns]
    
    # Create figure with subplots
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle(f'Design Pattern Analysis - {llm_name} Performance Report', 
                 fontsize=16, fontweight='bold')
    
   # Subplot 1: Success Rate by Pattern (Horizontal Bar Chart)
    ax1 = plt.subplot(2, 2, 1)
    colors = ['#2ecc71' if sr == 1.0 else '#e74c3c' if sr < 0.95 else '#f39c12' for sr in success_rates]
    y_pos = np.arange(len(patterns))
    bars = ax1.barh(y_pos, success_rates, color=colors, alpha=0.8, edgecolor='black')
    ax1.set_yticks(y_pos)
    ax1.set_yticklabels(patterns)
    ax1.set_xlabel('Success Rate', fontweight='bold')
    ax1.set_title('Success Rate by Design Pattern', fontweight='bold')
    # Dynamic x-axis limits based on actual data
    min_rate = min(success_rates)
    x_min = max(0.0, min_rate - 0.05)  # 5% padding below minimum
    ax1.set_xlim([x_min, 1.01])
    ax1.grid(axis='x', alpha=0.3)
    # Add percentage labels
    for i, (bar, rate) in enumerate(zip(bars, success_rates)):
        ax1.text(rate - 0.02, bar.get_y() + bar.get_height()/2, 
                 f'{rate:.0%}', va='center', ha='right', fontweight='bold', color='white')
    
   # Subplot 2: Success Rate by Difficulty Level
    ax2 = plt.subplot(2, 2, 2)
    if "success_rate_by_difficulty" in data:
        # Define order: Easy, Medium, Hard
        difficulty_order = ['E', 'M', 'H']
        difficulties = [d for d in difficulty_order if d in data["success_rate_by_difficulty"]]
        diff_success_rates = [data["success_rate_by_difficulty"][d]["success_rate"] for d in difficulties]
        diff_colors = ['#2ecc71', '#f39c12', '#e74c3c']  # Green for Easy, Orange for Medium, Red for Hard
        
        bars2 = ax2.bar(difficulties, diff_success_rates, color=diff_colors, alpha=0.8, edgecolor='black')
        ax2.set_xlabel('Difficulty Level', fontweight='bold')
        ax2.set_ylabel('Success Rate', fontweight='bold')
        ax2.set_title('Success Rate by Difficulty', fontweight='bold')
        ax2.set_ylim([0.9, 1.01])
        ax2.grid(axis='y', alpha=0.3)
        
        # Add percentage labels on bars
        for bar, rate in zip(bars2, diff_success_rates):
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                     f'{rate:.1%}', ha='center', va='bottom', fontweight='bold')
    else:
        # Fallback to total counts if difficulty data not available
        bars2 = ax2.bar(patterns, total_counts, color='#3498db', alpha=0.8, edgecolor='black')
        ax2.set_xlabel('Design Pattern', fontweight='bold')
        ax2.set_ylabel('Detection Count', fontweight='bold')
        ax2.set_title('Pattern Detection Frequency', fontweight='bold')
        ax2.tick_params(axis='x', rotation=45)
        ax2.grid(axis='y', alpha=0.3)
        for bar in bars2:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                     f'{int(height)}', ha='center', va='bottom', fontweight='bold')
    
    # Subplot 3: Success vs Failure Counts (Stacked Bar)
    ax3 = plt.subplot(2, 2, 3)
    x_pos = np.arange(len(patterns))
    p1 = ax3.bar(x_pos, success_counts, color='#2ecc71', alpha=0.8, label='Success', edgecolor='black')
    p2 = ax3.bar(x_pos, failure_counts, bottom=success_counts, color='#e74c3c', alpha=0.8, label='Failure', edgecolor='black')
    ax3.set_xticks(x_pos)
    ax3.set_xticklabels(patterns, rotation=45, ha='right')
    ax3.set_ylabel('Number of Records', fontweight='bold')
    ax3.set_title('Success vs Failure Distribution', fontweight='bold')
    ax3.legend()
    ax3.grid(axis='y', alpha=0.3)
    
    # Subplot 4: Time by Code Generator
    ax4 = plt.subplot(2, 2, 4)
    
    if "success_rate_by_generated_llm" in data:
        generators = list(data["success_rate_by_generated_llm"].keys())
        gen_times = [data["success_rate_by_generated_llm"][g]["average_time_seconds"] for g in generators]
        
        # Sort by time
        sorted_indices = sorted(range(len(gen_times)), key=lambda i: gen_times[i], reverse=True)
        sorted_generators = [generators[i] for i in sorted_indices]
        sorted_times = [gen_times[i] for i in sorted_indices]
        
        # Color code by time (relative to range)
        if len(sorted_times) > 1:
            max_time = max(sorted_times)
            min_time = min(sorted_times)
            time_range = max_time - min_time
            
            colors_gen = []
            for t in sorted_times:
                if time_range > 0:
                    normalized = (t - min_time) / time_range
                    if normalized > 0.66:
                        colors_gen.append('#e74c3c')  # Red - slowest
                    elif normalized > 0.33:
                        colors_gen.append('#f39c12')  # Orange - medium
                    else:
                        colors_gen.append('#2ecc71')  # Green - fastest
                else:
                    colors_gen.append('#3498db')  # All same
        else:
            colors_gen = ['#3498db'] * len(sorted_times)
        
        y_pos = np.arange(len(sorted_generators))
        bars4 = ax4.barh(y_pos, sorted_times, color=colors_gen, alpha=0.8, edgecolor='black')
        ax4.set_yticks(y_pos)
        ax4.set_yticklabels(sorted_generators)
        ax4.set_xlabel('Average Time (seconds)', fontweight='bold')
        ax4.set_title(f'{llm_name}: Analysis Time by Code Generator', fontweight='bold')
        ax4.grid(axis='x', alpha=0.3)
        
        # Add time labels
        for bar, time in zip(bars4, sorted_times):
            ax4.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                    f'{time:.2f}s', va='center', ha='left', fontweight='bold', fontsize=9)
        
        # Add insight text if there's a notable difference
        if len(sorted_times) > 1 and time_range > 0:
            time_diff = max_time - min_time
            if time_diff > 1.0:  # More than 1 second difference
                insight_text = f"Difference: {time_diff:.2f}s ({(time_diff/min_time)*100:.1f}% variation)"
                ax4.text(0.98, 0.02, insight_text, transform=ax4.transAxes,
                        ha='right', va='bottom', fontsize=8, style='italic',
                        bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.3))
    else:
        ax4.text(0.5, 0.5, 'Code generator time data not available', 
                transform=ax4.transAxes, ha='center', va='center',
                fontsize=12, style='italic')
        ax4.axis('off')
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"✓ Chart saved: {output_path}")

def create_summary_visualisation(data_list, output_path):
    """Create a summary visualisation comparing all LLMs."""
    if len(data_list) < 2:
        print("Skipping summary chart (need at least 2 LLMs to compare)")
        return
    
    # Extract data for all LLMs
    llm_names = [d["metadata"]["llm_name"] for d in data_list]
    
    # Get all unique patterns across all datasets
    all_patterns = set()
    for data in data_list:
        all_patterns.update(data["success_rate_per_pattern"].keys())
    patterns = sorted(list(all_patterns))
    
    # Create success rate matrix
    success_matrix = []
    total_records = []
    avg_times = []
    overall_success_rates = []
    
    for data in data_list:
        pattern_rates = []
        for pattern in patterns:
            if pattern in data["success_rate_per_pattern"]:
                rate = data["success_rate_per_pattern"][pattern]["success_rate"]
            else:
                rate = np.nan
            pattern_rates.append(rate)
        success_matrix.append(pattern_rates)
        total_records.append(data["metadata"]["total_records_analysed"])
        avg_times.append(data["average_analysis_time_seconds"])
        
        # Calculate overall success rate
        pattern_data = data["success_rate_per_pattern"]
        total_success = sum(p["success_count"] for p in pattern_data.values())
        total_count = sum(p["total_count"] for p in pattern_data.values())
        overall_success_rates.append(total_success / total_count if total_count > 0 else 0)
    
    success_matrix = np.array(success_matrix)
    
    # Create figure with subplots
    fig = plt.figure(figsize=(20, 12))
    fig.suptitle('Design Pattern Analysis - Multi-LLM Comparison Summary', 
                 fontsize=18, fontweight='bold')
    
    # Subplot 1: Heatmap of Success Rates
    ax1 = plt.subplot(2, 3, 1)
    im = ax1.imshow(success_matrix, cmap='RdYlGn', aspect='auto', vmin=0.85, vmax=1.0)
    ax1.set_xticks(np.arange(len(patterns)))
    ax1.set_yticks(np.arange(len(llm_names)))
    ax1.set_xticklabels(patterns, rotation=45, ha='right')
    ax1.set_yticklabels(llm_names)
    ax1.set_title('Success Rate Heatmap', fontweight='bold', pad=20)
    
    # Add text annotations
    for i in range(len(llm_names)):
        for j in range(len(patterns)):
            if not np.isnan(success_matrix[i, j]):
                _ = ax1.text(j, i, f'{success_matrix[i, j]:.0%}',
                               ha="center", va="center", color="black", fontsize=8)
    
    plt.colorbar(im, ax=ax1, label='Success Rate')
    
    # Subplot 2: Overall Success Rate Comparison
    ax2 = plt.subplot(2, 3, 2)
    colors_bar = ['#2ecc71' if sr >= 0.99 else '#f39c12' if sr >= 0.95 else '#e74c3c' 
                  for sr in overall_success_rates]
    bars = ax2.barh(llm_names, overall_success_rates, color=colors_bar, alpha=0.8, edgecolor='black')
    ax2.set_xlabel('Overall Success Rate', fontweight='bold')
    ax2.set_title('Overall LLM Performance', fontweight='bold')
    ax2.set_xlim([0.9, 1.01])
    ax2.grid(axis='x', alpha=0.3)
    
    for i, (bar, rate) in enumerate(zip(bars, overall_success_rates)):
        ax2.text(rate - 0.01, bar.get_y() + bar.get_height()/2, 
                 f'{rate:.2%}', va='center', ha='right', fontweight='bold', color='white')
    
    # Subplot 3: Average Analysis Time
    ax3 = plt.subplot(2, 3, 3)
    bars3 = ax3.barh(llm_names, avg_times, color='#3498db', alpha=0.8, edgecolor='black')
    ax3.set_xlabel('Average Time (seconds)', fontweight='bold')
    ax3.set_title('Average Analysis Time per Record', fontweight='bold')
    ax3.grid(axis='x', alpha=0.3)
    
    for bar, time in zip(bars3, avg_times):
        ax3.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2, 
                 f'{time:.1f}s', va='center', ha='left', fontweight='bold')
    
    # Subplot 4: Pattern Success Rate Comparison (Line Chart)
    ax4 = plt.subplot(2, 3, 4)
    x_pos = np.arange(len(patterns))
    for i, llm_name in enumerate(llm_names):
        ax4.plot(x_pos, success_matrix[i], marker='o', label=llm_name, linewidth=2)
    ax4.set_xticks(x_pos)
    ax4.set_xticklabels(patterns, rotation=45, ha='right')
    ax4.set_ylabel('Success Rate', fontweight='bold')
    ax4.set_title('Pattern-by-Pattern Comparison', fontweight='bold')
    ax4.set_ylim([0.80, 1.02])
    ax4.legend(loc='lower right')
    ax4.grid(alpha=0.3)
    ax4.axhline(y=1.0, color='green', linestyle='--', alpha=0.3, label='Perfect Score')
    ax4.axhline(y=0.95, color='orange', linestyle='--', alpha=0.3, label='95% Threshold')
    
    # Subplot 5: Total Records Processed
    ax5 = plt.subplot(2, 3, 5)
    bars5 = ax5.bar(llm_names, total_records, color='#9b59b6', alpha=0.8, edgecolor='black')
    ax5.set_ylabel('Total Records', fontweight='bold')
    ax5.set_title('Dataset Size Comparison', fontweight='bold')
    ax5.tick_params(axis='x', rotation=45)
    ax5.grid(axis='y', alpha=0.3)
    
    for bar in bars5:
        height = bar.get_height()
        ax5.text(bar.get_x() + bar.get_width()/2., height,
                 f'{int(height):,}', ha='center', va='bottom', fontweight='bold')
    
    # Subplot 6: Summary Statistics Table
    ax6 = plt.subplot(2, 3, 6)
    ax6.axis('off')
    
    # Calculate summary statistics
    best_performer = llm_names[np.argmax(overall_success_rates)]
    fastest_llm = llm_names[np.argmin(avg_times)]
    most_data = llm_names[np.argmax(total_records)]
    
    # Find most problematic pattern across all LLMs
    pattern_avg_success = np.nanmean(success_matrix, axis=0)
    worst_pattern_idx = np.argmin(pattern_avg_success)
    worst_pattern = patterns[worst_pattern_idx]
    
    summary_text = f"""
COMPARATIVE ANALYSIS SUMMARY
{'=' * 50}

LLMs Analysed: {len(llm_names)}
Total Patterns: {len(patterns)}

PERFORMANCE RANKINGS:
  - Best Overall: {best_performer}
     Success Rate: {max(overall_success_rates):.2%}
  
  - Fastest: {fastest_llm}
     Avg Time: {min(avg_times):.2f}s per record
  
  - Largest Dataset: {most_data}
     Records: {max(total_records):,}

PATTERN INSIGHTS:
  • Most Challenging: {worst_pattern}
    Avg Success: {pattern_avg_success[worst_pattern_idx]:.1%}
  
  • Perfect Patterns: {sum(np.all(success_matrix[:, i] == 1.0) for i in range(len(patterns)))} patterns
    with 100% success across all LLMs

CONSISTENCY:
  • Success Rate Range: {min(overall_success_rates):.1%} - {max(overall_success_rates):.1%}
  • Time Range: {min(avg_times):.1f}s - {max(avg_times):.1f}s
"""
    
    ax6.text(0.05, 0.95, summary_text, transform=ax6.transAxes, 
             fontsize=11, verticalalignment='top', fontfamily='monospace',
             bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.3))
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"✓ Summary chart saved: {output_path}")

def main():
    # Define paths
    script_dir = Path(__file__).parent
    analysis_dir = script_dir / "Analysis"
    charts_dir = script_dir / "Charts"
    
    # Create Charts directory if it doesn't exist
    charts_dir.mkdir(exist_ok=True)
    print(f"Charts directory: {charts_dir}")
    
    # Load all analysis files
    print(f"\nLoading analysis files from: {analysis_dir}")
    data_list = load_analysis_files(analysis_dir)
    
    if not data_list:
        print("No analysis files to process. Exiting.")
        return
    
    print(f"\nFound {len(data_list)} analysis file(s)")
    
    # Generate charts for each analysis file
    print("\nGenerating individual charts...")
    for data in data_list:
        llm_name = data["metadata"]["llm_name"]
        output_filename = f"chart_{llm_name}.png"
        output_path = charts_dir / output_filename
        
        try:
            create_visualisation(data, output_path)
        except Exception as e:
            print(f"✗ Error creating chart for {llm_name}: {e}")
    
    # Generate summary comparison chart
    print("\nGenerating summary comparison chart...")
    summary_output = charts_dir / "chart_summary_all.png"
    try:
        create_summary_visualisation(data_list, summary_output)
    except Exception as e:
        print(f"✗ Error creating summary chart: {e}")
    
    print(f"\n{'='*50}")
    print(f"Processing complete! Generated {len(data_list)} individual chart(s)")
    print("+ 1 summary comparison chart")
    print(f"Charts saved in: {charts_dir}")
    print(f"{'='*50}")

if __name__ == "__main__":
    main()