"""
================================================================================
AI-GENERATED CODE DISCLAIMER
================================================================================
This file was fully generated by AI using Claude Sonnet 4.5 on 01/10/2025.

Purpose: Visual representation of design pattern recognition analysis data
         collected from various LLM models.

The script automatically processes analysis JSON files and generates
comprehensive visualisation charts for performance comparison.
================================================================================
"""

import matplotlib.pyplot as plt
import numpy as np
import json
from pathlib import Path

def load_analysis_files(analysis_dir):
    """Load all analysis JSON files from the specified directory."""
    analysis_path = Path(analysis_dir)
    json_files = list(analysis_path.glob("analysis_*.json"))
    
    if not json_files:
        print(f"No analysis files found in {analysis_dir}")
        return []
    
    data_list = []
    for json_file in json_files:
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
                data['_filename'] = json_file.name
                data_list.append(data)
            print(f"✓ Loaded: {json_file.name}")
        except Exception as e:
            print(f"✗ Error loading {json_file.name}: {e}")
    
    return data_list

def create_visualisation(data, output_path):
    """Create visualisation for a single analysis dataset."""
    llm_name = data["metadata"]["llm_name"]
    
    # Extract pattern data
    patterns = list(data["success_rate_per_pattern"].keys())
    success_rates = [data["success_rate_per_pattern"][p]["success_rate"] for p in patterns]
    total_counts = [data["success_rate_per_pattern"][p]["total_count"] for p in patterns]
    failure_counts = [data["success_rate_per_pattern"][p]["failure_count"] for p in patterns]
    success_counts = [data["success_rate_per_pattern"][p]["success_count"] for p in patterns]
    
    # Create figure with subplots
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle(f'Design Pattern Analysis - {llm_name} Performance Report', 
                 fontsize=16, fontweight='bold')
    
    # Subplot 1: Success Rate by Pattern (Horizontal Bar Chart)
    ax1 = plt.subplot(2, 2, 1)
    colors = ['#2ecc71' if sr == 1.0 else '#e74c3c' if sr < 0.95 else '#f39c12' for sr in success_rates]
    y_pos = np.arange(len(patterns))
    bars = ax1.barh(y_pos, success_rates, color=colors, alpha=0.8, edgecolor='black')
    ax1.set_yticks(y_pos)
    ax1.set_yticklabels(patterns)
    ax1.set_xlabel('Success Rate', fontweight='bold')
    ax1.set_title('Success Rate by Design Pattern', fontweight='bold')
    ax1.set_xlim([0.85, 1.01])
    ax1.grid(axis='x', alpha=0.3)
    # Add percentage labels
    for i, (bar, rate) in enumerate(zip(bars, success_rates)):
        ax1.text(rate - 0.02, bar.get_y() + bar.get_height()/2, 
                 f'{rate:.0%}', va='center', ha='right', fontweight='bold', color='white')
    
    # Subplot 2: Total Records Analysed per Pattern
    ax2 = plt.subplot(2, 2, 2)
    bars2 = ax2.bar(patterns, total_counts, color='#3498db', alpha=0.8, edgecolor='black')
    ax2.set_xlabel('Design Pattern', fontweight='bold')
    ax2.set_ylabel('Number of Records', fontweight='bold')
    ax2.set_title('Records Analysed per Pattern', fontweight='bold')
    ax2.tick_params(axis='x', rotation=45)
    ax2.grid(axis='y', alpha=0.3)
    # Add count labels on bars
    for bar in bars2:
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height,
                 f'{int(height)}', ha='center', va='bottom', fontweight='bold')
    
    # Subplot 3: Success vs Failure Counts (Stacked Bar)
    ax3 = plt.subplot(2, 2, 3)
    x_pos = np.arange(len(patterns))
    p1 = ax3.bar(x_pos, success_counts, color='#2ecc71', alpha=0.8, label='Success', edgecolor='black')
    p2 = ax3.bar(x_pos, failure_counts, bottom=success_counts, color='#e74c3c', alpha=0.8, label='Failure', edgecolor='black')
    ax3.set_xticks(x_pos)
    ax3.set_xticklabels(patterns, rotation=45, ha='right')
    ax3.set_ylabel('Number of Records', fontweight='bold')
    ax3.set_title('Success vs Failure Distribution', fontweight='bold')
    ax3.legend()
    ax3.grid(axis='y', alpha=0.3)
    
    # Subplot 4: Summary Statistics (Text Box)
    ax4 = plt.subplot(2, 2, 4)
    ax4.axis('off')
    
    # Get timestamp if available
    timestamp = data["metadata"].get("generation_timestamp", "N/A")
    
    summary_text = f"""
ANALYSIS SUMMARY
{'=' * 40}

LLM Model: {llm_name}
Generated: {timestamp}
Total Records: {data['metadata']['total_records_analysed']:,}

TIMING STATISTICS:
  • Total Time: {data['total_analysis_time_hours']:.2f} hours
  • Average Time: {data['average_analysis_time_seconds']:.2f} sec
  • Min Time: {data['min_analysis_time_seconds']:.2f} sec
  • Max Time: {data['max_analysis_time_seconds']:.2f} sec

PATTERN STATISTICS:
  • Total Patterns: {len(patterns)}
  • Perfect Success: {sum(1 for sr in success_rates if sr == 1.0)} patterns
  • Total Failures: {sum(failure_counts)} records
  • Overall Success Rate: {sum(success_counts) / sum(total_counts):.1%}

PATTERNS WITH ISSUES:"""
    
    # Add patterns with failures
    patterns_with_failures = [(p, failure_counts[i], success_rates[i]) 
                              for i, p in enumerate(patterns) if failure_counts[i] > 0]
    patterns_with_failures.sort(key=lambda x: x[1], reverse=True)
    
    if patterns_with_failures:
        for pattern, failures, rate in patterns_with_failures:
            summary_text += f"\n  • {pattern}: {failures} failures ({rate:.0%})"
    else:
        summary_text += "\n  • None - Perfect Performance!"
    
    ax4.text(0.1, 0.95, summary_text, transform=ax4.transAxes, 
             fontsize=10, verticalalignment='top', fontfamily='monospace',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.3))
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"✓ Chart saved: {output_path}")

def main():
    # Define paths
    script_dir = Path(__file__).parent
    analysis_dir = script_dir / "Analysis"
    charts_dir = script_dir / "Charts"
    
    # Create Charts directory if it doesn't exist
    charts_dir.mkdir(exist_ok=True)
    print(f"Charts directory: {charts_dir}")
    
    # Load all analysis files
    print(f"\nLoading analysis files from: {analysis_dir}")
    data_list = load_analysis_files(analysis_dir)
    
    if not data_list:
        print("No analysis files to process. Exiting.")
        return
    
    print(f"\nFound {len(data_list)} analysis file(s)")
    
    # Generate charts for each analysis file
    print("\nGenerating charts...")
    for data in data_list:
        llm_name = data["metadata"]["llm_name"]
        output_filename = f"chart_{llm_name}.png"
        output_path = charts_dir / output_filename
        
        try:
            create_visualisation(data, output_path)
        except Exception as e:
            print(f"✗ Error creating chart for {llm_name}: {e}")
    
    print(f"\n{'='*50}")
    print(f"Processing complete! Generated {len(data_list)} chart(s)")
    print(f"Charts saved in: {charts_dir}")
    print(f"{'='*50}")

if __name__ == "__main__":
    main()