import argparse
import os
import sys

from catalogue import WorkflowType, DESIGN_PATTERNS, DIFFICULTY_LEVELS,LLM_PROVIDERS

def create_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Design Pattern Recogniser - Analyse code snippets to identify design patterns",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""

Examples:
 # Use Claude to analyse ALL code snippets using single-prompt workflow
 python PatternRecogniser.py --llm claude 
 
 # Use OpenAI to analyse medium difficulty Factory patterns (all matching)
 python PatternRecogniser.py --llm openai --filter-pattern Factory --filter-difficulty M
 
 # Use Claude to analyse 5 hard Observer patterns originally generated by GPT
 python PatternRecogniser.py --llm claude --filter-llm openai --filter-pattern Observer --filter-difficulty H --count 5 
 
 # Use KimiK2 to analyse 10 easy Singleton snippets (multi-layered workflow)
 python PatternRecogniser.py --llm kimi --workflow multi --filter-pattern Singleton --filter-difficulty E --count 10 

# Analyse a custom file from Input folder
 python PatternRecogniser.py --llm claude --input my_code.py

Available Design Patterns:
 Singleton, Factory, Builder, Prototype,
 Adapter, Decorator, Facade, Proxy,
 Observer, Strategy, Command, Iterator, State

Difficulty Levels:
 E = Easy (basic implementation)
 M = Medium (standard implementation with features)
 H = Hard (complex implementation with advanced features)

LLM Providers:
 grok - Grok-code-fast-1
 openai - OpenAI GPT  
 claude - Anthorpic Claude
 grok - xAI Grok 4 Fast
 kimi - Kimi K2
"""
    )

    # LLM that will be analysing the code snippet(s)
    parser.add_argument('--llm', 
        type=str,
        help=f'Filter by LLM identify ({LLM_PROVIDERS[0]}, {LLM_PROVIDERS[1]}, etc.)'
    )

    # Custom input file option
    parser.add_argument('--input', '-i',
        type=str,
        help='Analyse a custom Python file from the Input folder (e.g., my_code.py)'
    )

    # The analysing workflow type (singlepromot or complex multilayer)
    parser.add_argument('--workflow', '-w', 
        type=str, 
        choices=['single', 'multi'], 
        default='single', 
        help='Analyse workflow type'
    )


    ######### FILTERING 
    filter_group = parser.add_argument_group('snippet filtering options',
                                             'Options to select which code snippets to analyse '
                                             '(only applies when using dataset, not with --input)')
    
    filter_group.add_argument('--filter-llm',
        type=str,
        choices=LLM_PROVIDERS,
        help='Filter snippets by the LLM that originally generated them')

    filter_group.add_argument('--filter-pattern', '-p',
        type=str,
        choices=DESIGN_PATTERNS,
        help="Filter snippets by specific design pattern"
        )

    filter_group.add_argument('--filter-difficulty', '-d',
        type=str,
        choices=DIFFICULTY_LEVELS,
        help="Filter snippets by implementation difficulty level"
        )
    
    filter_group.add_argument('--count', '-c',
        type=int,
        help="Number of code snippets to process (if not specified, process all matching snippets)"
        )
    
    # Potential filter args:
    # --exclude-patterns
    # --exclude-llms
    #

    return parser


def validate_arguments(args: argparse.Namespace) -> argparse.Namespace:
        """Validate and normalise command line arguments"""
        #### Mandatory args
        # Workflow type
        if args.workflow == 'multi':
            args.workflow = WorkflowType.MULTI_LAYERED
        else:
            args.workflow = WorkflowType.SINGLE_PROMPT


        # LLM provider    
        if args.llm is None:
            print("Missing LLM Provider! add --llm <llm provider>")
            print(f"Available providers: {', '.join(LLM_PROVIDERS)}")
            sys.exit(1)
        elif args.llm not in LLM_PROVIDERS:
            print(f"Error: Unsupposrted LLM provider '{args.llm}'")
            print(f"Available providers: {', '.join(LLM_PROVIDERS)}")
            sys.exit(1)


        # Custom input handling
        if args.input:
            # Validate custom input file
            input_path = os.path.join('Input', args.input)

            if not os.path.exists(input_path):
                print(f"Error: Input file '{args.input}' not found in Input folder")
                sys.exit(1)

            if not input_path.endswith('.py'):
                print("Error: Input file must be a Python (.py) file")
                sys.exit(1)
            # Store full path
            args.input_path = input_path

            # Note if filters are specified (they will be ignored for custom input)
            if args.filter_llm or args.filter_pattern or args.filter_difficulty or args.count:
                print("Warning: Filter options (--filter-llm, --filter-pattern, --filter-difficulty, --count) are ignored when using --input")
        
            # Return early since we're not using dataset
            return args
        
        # No custom input - null it
        args.input_path = None


        #### Optional Args
        # Design Pattern
        if args.filter_pattern is not None and args.filter_pattern not in DESIGN_PATTERNS:
            print(f"Error: Unknown design pattern '{args.filter_pattern}'")
            print(f"Available patterns: {', '.join(DESIGN_PATTERNS)}")
            sys.exit(1)

        # Complexity level
        if args.filter_difficulty is not None and args.filter_difficulty not in DIFFICULTY_LEVELS:
            print(f"Error: Invalid difficulty level '{args.filter_difficulty}'")
            print(f"Available levels: {','.join(DIFFICULTY_LEVELS)} (E=Easy, M=Medium, H=Hard)")
            sys.exit(1)

        
        # Validate count (if any)
        if args.count is not None:
            if args.count <= -1: # clamp to -1 (all code snippets)
                print(f"Warning: count {args.count} clamped to -1 (all snippets)")
                args.count = -1
            elif args.count == 0:
                print("Count cannot be 0, use -1 for ALL or a positive number")
                sys.exit(1)
        else:
            args.count = -1
           

        
        return args
